heroku-admin/config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'

  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

heroku-admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

heroku-admin/app/models/customer.rb
class Customer < ApplicationRecord
end

heroku-admin/app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

heroku-admin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

heroku-admin/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :bill)
    end
end

heroku-admin/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :description, :address)
      # params.fetch(:shop, {})
    end
end

heroku-admin/app/helpers/application_helper.rb
module ApplicationHelper
end

heroku-admin/app/helpers/customers_helper.rb
module CustomersHelper
end

heroku-admin/app/helpers/shops_helper.rb
module ShopsHelper
end

heroku-admin/app/views/customers/_form.html.slim
= form_for @customer do |f|
  - if @customer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      ul
        - @customer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :bill
    = f.number_field :bill
  .actions = f.submit

heroku-admin/app/views/customers/edit.html.slim
h1 Editing customer

== render 'form'

=> link_to 'Show', @customer
'|
=< link_to 'Back', customers_path

heroku-admin/app/views/customers/index.html.slim
h1 Listing customers

table
  thead
    tr
      th Name
      th Email
      th Bill
      th
      th
      th

  tbody
    - @customers.each do |customer|
      tr
        td = customer.name
        td = customer.email
        td = customer.bill
        td = link_to 'Show', customer
        td = link_to 'Edit', edit_customer_path(customer)
        td = link_to 'Destroy', customer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Customer', new_customer_path

heroku-admin/app/views/customers/new.html.slim
h1 New customer

== render 'form'

= link_to 'Back', customers_path

heroku-admin/app/views/customers/show.html.slim
p#notice = notice

p
  strong Name:
  = @customer.name
p
  strong Email:
  = @customer.email
p
  strong Bill:
  = @customer.bill

=> link_to 'Edit', edit_customer_path(@customer)
'|
=< link_to 'Back', customers_path

heroku-admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>HerokuAdmin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>

  </style>
</head>
<body>

  <div class="container-fluid">
    <div class="row content">

      <div class="col-sm-3 sidenav">
        <h4>Dashboard</h4>
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#section1">Home</a></li>
          <li><a href="#section2">Shop</a></li>
          <li><a href="#section3">Product</a></li>
          <li><a href="#section3">Information</a></li>
        </ul><br>
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </div>

      <div class="col-sm-9">
        <%= yield %>
      </div>
    </div>
  </div>

  <footer class="container-fluid">
    <p>Footer Text</p>
  </footer>

</body>
</html>

heroku-admin/app/views/shops/_form.html.slim
h2
  | Create new shop

= form_for shop, method: :post, local: true, class: "form-horizontal" do |form|
  div.form-group
    lable.control-label.col-sm-2 for="name"
      | Name:
    div.col-sm-10
      = form.text_field :name, placeholder: "Enter shop name"
  div.form-group
    lable.control-label.col-sm-2 for="description"
      | Description:
    div.col-sm-10
      = form.text_field :description, placeholder: "Enter description"
  div.form-group
    lable.control-label.col-sm-2 for="address"
      | Address:
    div.col-sm-10
      = form.text_field :address, placeholder: "Enter address"
  div.form-group
    div.col-sm-offset-2.col-sm-10
      = form.submit "Create"

heroku-admin/app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

heroku-admin/app/views/shops/index.html.slim
p#notice
  = notice

h1
  | Shops

table
  thead
    tr
      th colspan="3"
  tbody
    - @shops.each do |shop|
      tr
        td = shop.name
        td = link_to 'Show', shop
        td = link_to 'Edit', edit_shop_path(shop)
        td = link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' }

.btn.btn-default
  = link_to 'New Shop', new_shop_path

heroku-admin/app/views/shops/new.html.slim
<h1>New Shop</h1>

= render 'form', shop: @shop
.btn.btn-default
  = link_to 'Back', shops_path

heroku-admin/app/views/shops/show.html.slim
p#notice
  = notice
p
  | Shop:
  = @shop.name
p
  = @shop.description
p
  = @shop.address
.btn.btn-default
  = link_to 'Edit', edit_shop_path(@shop)
.btn.btn-default
  = link_to 'Back', shops_path